import { generateProviderProfile } from "./ai-profile";
import { matchReferralToProviders } from "./referral-matching";
import type {
  ActivityLog,
  BusinessPartner,
  NetworkParticipant,
  Provider,
  ReferralSource,
  Referral,
  RevenueTracking,
  ShareCard,
  SourceChannel,
  User,
} from "./types";

export const users: User[] = [
  {
    id: "user-admin",
    name: "Alex 平台管理员",
    email: "admin@careslink.ai",
    role: "admin",
  },
  {
    id: "user-operator",
    name: "Grace Chen",
    email: "grace@careslink.ai",
    role: "business_partner",
    partnerId: "partner-chen",
  },
  {
    id: "user-provider",
    name: "Harbour Intake 团队",
    email: "intake@harbour.example",
    role: "provider",
    providerId: "provider-harbour",
  },
  {
    id: "user-referral-source",
    name: "Lily 社区资源方",
    email: "lily@community.example",
    role: "referral_source",
    partnerId: "partner-chen",
  },
];

export const businessPartners: BusinessPartner[] = [
  {
    id: "partner-chen",
    name: "悉尼养老 Referral 资源群",
    operatorName: "Grace Chen",
    primaryRegion: "Greater Sydney",
    sourceGroups: [
      "悉尼养老 Referral 资源群",
      "NSW 华人 NDIS 服务商群",
    ],
    providerCount: 48,
    referralCount: 126,
    revenueShareRate: 0.3,
    status: "pilot",
  },
  {
    id: "partner-lee",
    name: "布里斯班服务商资源圈",
    operatorName: "Michael Lee",
    primaryRegion: "Brisbane",
    sourceGroups: ["布里斯班服务商资源圈"],
    providerCount: 18,
    referralCount: 34,
    revenueShareRate: 0.25,
    status: "paused",
  },
];

export const networkParticipants: NetworkParticipant[] = [
  {
    id: "participant-sydney-source",
    organizationName: "悉尼华人 Support Coordination Circle",
    role: "referral_source",
    canSendReferrals: true,
    canReceiveReferrals: false,
    status: "approved",
    contactName: "Lily Wang",
    contactEmail: "lily@community.example",
    contactPhone: "04 2222 1111",
    serviceFocus: ["Support Coordination", "Personal Care"],
    regions: ["Sydney", "Parramatta", "Hurstville"],
    sourcePartnerId: "partner-chen",
    sourceGroupName: "悉尼养老 Referral 资源群",
    sourceInviteLink: "invite-source-001",
    createdBy: "user-operator",
    reviewedBy: "user-admin",
    notes: "主要提供真实 referral 来源，需要记录需求质量和跟进责任人。",
    createdAt: "2026-06-16",
  },
  {
    id: "participant-harbour-provider",
    organizationName: "Harbour Community Support",
    role: "service_provider",
    canSendReferrals: false,
    canReceiveReferrals: true,
    status: "approved",
    contactName: "Harbour Intake 团队",
    contactEmail: "hello@harbour.example",
    contactPhone: "02 9000 1000",
    serviceFocus: ["Support Coordination", "Personal Care"],
    regions: ["Sydney", "Parramatta", "Chatswood"],
    sourcePartnerId: "partner-chen",
    sourceGroupName: "NSW 华人 NDIS 服务商群",
    sourceInviteLink: "invite-001",
    createdBy: "user-operator",
    reviewedBy: "user-admin",
    notes: "主要接收匹配机会，需要审核 ABN、保险、服务区域和接单能力。",
    createdAt: "2026-06-18",
  },
  {
    id: "participant-compass-both",
    organizationName: "Compass Home Care",
    role: "both",
    canSendReferrals: true,
    canReceiveReferrals: true,
    status: "approved",
    contactName: "Compass Intake",
    contactEmail: "referrals@compass.example",
    contactPhone: "02 9222 3000",
    serviceFocus: ["Domestic Assistance", "Personal Care", "Transport"],
    regions: ["Parramatta", "Blacktown", "Penrith"],
    sourcePartnerId: "partner-chen",
    sourceGroupName: "悉尼养老 Referral 资源群",
    sourceInviteLink: "invite-003",
    createdBy: "user-operator",
    reviewedBy: "user-admin",
    notes: "既有 package manager 来源，也承接 aged care referral，需要标注利益冲突边界。",
    createdAt: "2026-06-20",
  },
];

export const referralSources: ReferralSource[] = [
  {
    id: "source-lily",
    participantId: "participant-sydney-source",
    organizationName: "悉尼华人 Support Coordination Circle",
    commonReferralTypes: ["Support Coordination", "Occupational Therapy"],
    usualRegions: ["Sydney", "Parramatta", "Hurstville"],
    sourcePartnerId: "partner-chen",
    sourceGroupName: "悉尼养老 Referral 资源群",
    trustNotes: "来源方可发布 referral，需要业务合伙人确认联系人和需求真实性。",
  },
  {
    id: "source-compass",
    participantId: "participant-compass-both",
    organizationName: "Compass Home Care",
    commonReferralTypes: ["Domestic Assistance", "Transport"],
    usualRegions: ["Blacktown", "Penrith"],
    sourcePartnerId: "partner-chen",
    sourceGroupName: "悉尼养老 Referral 资源群",
    trustNotes: "既发也接，匹配时应保留分配理由和运营方确认记录。",
  },
];

export const providers: Provider[] = [
  {
    id: "provider-harbour",
    name: "Harbour Community Support",
    serviceTypes: ["Support Coordination", "Personal Care"],
    serviceAreas: ["Sydney", "Parramatta", "Chatswood"],
    languages: ["English", "Mandarin", "Cantonese"],
    contact: {
      phone: "02 9000 1000",
      email: "hello@harbour.example",
      wechat: "harbour-care",
      website: "https://harbour.example",
    },
    abn: "12 345 678 901",
    status: "approved",
    acceptsNewClients: true,
    supportsNdis: true,
    supportsAgedCare: true,
    urgentCapacity: true,
    chineseProvider: true,
    qualifications:
      "注册 NDIS 服务商，配有双语支持协调员和已投保护理人员。",
    insuranceStatus: "verified",
    intro:
      "双语 care coordination 团队，帮助大悉尼家庭处理 NDIS 和养老护理 referral。",
    logoUrl: "/provider-harbour.png",
    sourcePartnerId: "partner-chen",
    sourceGroupName: "悉尼养老 Referral 资源群",
    sourceInviteLink: "invite-001",
    sourceShareCardId: "share-provider-harbour",
    membershipPlan: "Pro",
    createdBy: "user-operator",
    reviewedBy: "user-admin",
    createdAt: "2026-06-01",
  },
  {
    id: "provider-sunrise",
    name: "Sunrise Allied Health",
    serviceTypes: ["Physiotherapy", "Occupational Therapy"],
    serviceAreas: ["Sydney", "Hurstville", "Bankstown"],
    languages: ["English", "Mandarin", "Arabic"],
    contact: {
      phone: "02 9111 2000",
      email: "intake@sunrise.example",
      website: "https://sunrise.example",
    },
    abn: "21 456 789 012",
    status: "pending",
    acceptsNewClients: true,
    supportsNdis: true,
    supportsAgedCare: false,
    urgentCapacity: false,
    chineseProvider: true,
    qualifications:
      "具备 NDIS 经验的移动 allied health 团队，可提供上门评估。",
    insuranceStatus: "uploaded",
    intro:
      "面向 NDIS participant 的移动 allied health 服务，支持治疗和功能评估。",
    logoUrl: "/provider-sunrise.png",
    sourcePartnerId: "partner-chen",
    sourceGroupName: "NSW 华人 NDIS 服务商群",
    sourceInviteLink: "invite-002",
    sourceShareCardId: "share-provider-sunrise",
    membershipPlan: "Free",
    createdBy: "user-operator",
    reviewedBy: null,
    createdAt: "2026-06-08",
  },
  {
    id: "provider-compass",
    name: "Compass Home Care",
    serviceTypes: ["Domestic Assistance", "Personal Care", "Transport"],
    serviceAreas: ["Parramatta", "Blacktown", "Penrith"],
    languages: ["English", "Hindi", "Punjabi"],
    contact: {
      phone: "02 9222 3000",
      email: "referrals@compass.example",
    },
    abn: "31 567 890 123",
    status: "approved",
    acceptsNewClients: true,
    supportsNdis: false,
    supportsAgedCare: true,
    urgentCapacity: true,
    chineseProvider: false,
    qualifications:
      "养老护理支持人员已完成 police check，具备保险和社区交通服务覆盖。",
    insuranceStatus: "verified",
    intro:
      "专注 aged care package 的居家支持团队，提供交通、个人护理和家务协助。",
    logoUrl: "/provider-compass.png",
    sourcePartnerId: "partner-chen",
    sourceGroupName: "悉尼养老 Referral 资源群",
    sourceInviteLink: "invite-003",
    sourceShareCardId: "share-provider-compass",
    membershipPlan: "Agency",
    createdBy: "user-operator",
    reviewedBy: "user-admin",
    createdAt: "2026-06-12",
  },
  {
    id: "provider-rivergum",
    name: "Rivergum Plan Management",
    serviceTypes: ["Plan Management", "Support Coordination"],
    serviceAreas: ["Melbourne", "Geelong"],
    languages: ["English", "Mandarin", "Vietnamese"],
    contact: {
      phone: "03 9333 4000",
      email: "team@rivergum.example",
      wechat: "rivergum-plan",
    },
    abn: "41 678 901 234",
    status: "rejected",
    acceptsNewClients: false,
    supportsNdis: true,
    supportsAgedCare: false,
    urgentCapacity: false,
    chineseProvider: true,
    qualifications: "计划管理团队，资料仍待重新核验。",
    insuranceStatus: "missing",
    intro:
      "正在拓展维州市场的 NDIS 计划管理和协调服务。",
    logoUrl: "/provider-rivergum.png",
    sourcePartnerId: "partner-lee",
    sourceGroupName: "布里斯班服务商资源圈",
    sourceInviteLink: "invite-004",
    sourceShareCardId: "share-provider-rivergum",
    membershipPlan: "Free",
    createdBy: "user-operator",
    reviewedBy: "user-admin",
    createdAt: "2026-06-14",
  },
];

export const referrals: Referral[] = [
  {
    id: "referral-001",
    clientArea: "Parramatta",
    needType: "Support Coordination",
    languageRequirements: ["Mandarin"],
    frequency: "Weekly",
    urgent: true,
    fundingType: "NDIS",
    summary:
      "帕拉马塔一位普通话 participant 需要紧急支持协调。",
    contactName: "Referral 合作方",
    contactPhone: "04 0000 0000",
    sourcePartnerId: "partner-chen",
    sourceGroupName: "悉尼养老 Referral 资源群",
    sourceChannelId: "channel-wechat-sydney",
    status: "Pending Match",
    notes: "来自微信群讨论。家属希望有双语 intake。",
    followUpDate: "2026-06-24",
    assignedProviderId: null,
    matchedProviderIds: ["provider-harbour", "provider-sunrise"],
    createdBy: "user-operator",
    followedBy: "user-operator",
    createdAt: "2026-06-21",
  },
  {
    id: "referral-002",
    clientArea: "Blacktown",
    needType: "Domestic Assistance",
    languageRequirements: ["Hindi"],
    frequency: "Fortnightly",
    urgent: false,
    fundingType: "Aged Care",
    summary:
      "黑镇附近一位长者需要家务协助和交通支持。",
    contactName: "社区资源方",
    contactPhone: "04 1111 2222",
    sourcePartnerId: "partner-chen",
    sourceGroupName: "悉尼养老 Referral 资源群",
    sourceChannelId: "channel-share-domestic",
    status: "Contacted",
    notes: "已联系 Compass，等待 package manager 确认。",
    followUpDate: "2026-06-25",
    assignedProviderId: "provider-compass",
    matchedProviderIds: ["provider-compass"],
    createdBy: "user-operator",
    followedBy: "user-operator",
    createdAt: "2026-06-20",
  },
  {
    id: "referral-003",
    clientArea: "Hurstville",
    needType: "Occupational Therapy",
    languageRequirements: ["Mandarin"],
    frequency: "Assessment",
    urgent: false,
    fundingType: "NDIS",
    summary:
      "Participant 需要 OT 功能评估，并希望能和家属双语沟通。",
    contactName: "支持协调员",
    contactPhone: "04 3333 4444",
    sourcePartnerId: "partner-chen",
    sourceGroupName: "NSW 华人 NDIS 服务商群",
    sourceChannelId: "channel-wechat-ndis",
    status: "Matched",
    notes: "Sunrise 资料已回发到群里。",
    followUpDate: "2026-06-23",
    assignedProviderId: "provider-sunrise",
    matchedProviderIds: ["provider-sunrise"],
    createdBy: "user-operator",
    followedBy: "user-operator",
    createdAt: "2026-06-19",
  },
];

export const providerProfiles = providers.map(generateProviderProfile);

export const referralMatches = referrals.flatMap((referral) =>
  matchReferralToProviders(referral, providers),
);

export const sourceChannels: SourceChannel[] = [
  {
    id: "channel-wechat-sydney",
    partnerId: "partner-chen",
    name: "悉尼养老 Referral 资源群",
    type: "WeChat Group",
    providerCount: 31,
    referralCount: 78,
  },
  {
    id: "channel-wechat-ndis",
    partnerId: "partner-chen",
    name: "NSW 华人 NDIS 服务商群",
    type: "WeChat Group",
    providerCount: 17,
    referralCount: 48,
  },
  {
    id: "channel-share-domestic",
    partnerId: "partner-chen",
    name: "家务协助分享卡片",
    type: "Share Card",
    providerCount: 5,
    referralCount: 14,
  },
];

export const shareCards: ShareCard[] = [
  {
    id: "share-provider-harbour",
    type: "provider",
    providerId: "provider-harbour",
    sourcePartnerId: "partner-chen",
    sourceGroupName: "悉尼养老 Referral 资源群",
    channel: "WeChat",
    title: "Harbour Community Support",
    summary:
      "覆盖悉尼和帕拉马塔的双语 NDIS / 养老护理支持协调服务。",
    cta: "查看资料 / 联系服务商",
    qrLabel: "cares.link/harbour",
    createdAt: "2026-06-18",
  },
  {
    id: "share-referral-001",
    type: "referral",
    referralId: "referral-001",
    sourcePartnerId: "partner-chen",
    sourceGroupName: "悉尼养老 Referral 资源群",
    channel: "WhatsApp",
    title: "紧急支持协调 Referral",
    summary:
      "帕拉马塔 participant 需要普通话支持协调。",
    cta: "接单 / 联系运营方",
    qrLabel: "cares.link/r/ref001",
    createdAt: "2026-06-21",
  },
];

export const activityLogs: ActivityLog[] = [
  {
    id: "activity-001",
    actorId: "user-operator",
    entityType: "provider",
    entityId: "provider-sunrise",
    action: "提交服务商资料待审核",
    createdAt: "2026-06-21 09:12",
  },
  {
    id: "activity-002",
    actorId: "user-operator",
    entityType: "referral",
    entityId: "referral-001",
    action: "将 referral 匹配给两个服务商",
    createdAt: "2026-06-21 10:04",
  },
  {
    id: "activity-003",
    actorId: "user-admin",
    entityType: "share_card",
    entityId: "share-provider-harbour",
    action: "生成微信群服务商分享卡片",
    createdAt: "2026-06-21 10:31",
  },
];

export const revenueTracking: RevenueTracking[] = [
  {
    id: "rev-001",
    partnerId: "partner-chen",
    providerId: "provider-harbour",
    plan: "Pro",
    estimatedMonthlyValue: 129,
    partnerShareEstimate: 38.7,
    status: "future",
  },
  {
    id: "rev-002",
    partnerId: "partner-chen",
    providerId: "provider-compass",
    referralId: "referral-002",
    plan: "Agency",
    estimatedMonthlyValue: 349,
    partnerShareEstimate: 104.7,
    status: "tracking",
  },
];
